/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import res.audio.AePlayWave;
import res.audio.PlayAudio;

/**
 *
 * @author miguel
 */
public class LocalGame extends javax.swing.JFrame {

    /**
     * Creates new form LocalGame
     */
    public LocalGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtP2 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 625));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/icon.png"))); // NOI18N
        jLabel1.setText("Mr.Gato Game");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Player 1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(txtP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, -1));

        jLabel3.setText("Player 2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(txtP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 250, 70));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/box.jpg"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        btnPress(btn8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if(txtP1.getText().isEmpty() || txtP2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The names are not defined");
        }else{ 
            if(btnStart.getText().equals("Start")){
                btnStart.setText("Restart");
                Random r = new Random();
                if(r.nextBoolean())
                    turn=1;
                else
                    turn=-1;
                paint();
                nTurns = 0;
                btn0.setActionCommand("");btn1.setActionCommand("");btn2.setActionCommand("");
                btn3.setActionCommand("");btn4.setActionCommand("");btn5.setActionCommand("");
                btn6.setActionCommand("");btn7.setActionCommand("");btn8.setActionCommand("");
                btn0.setEnabled(true);btn1.setEnabled(true);btn2.setEnabled(true);
                btn3.setEnabled(true);btn4.setEnabled(true);btn5.setEnabled(true);
                btn6.setEnabled(true);btn7.setEnabled(true);btn8.setEnabled(true);
            }else{
                if(JOptionPane.showConfirmDialog(null, "Are you sure?")==0){
                    btnStart.setText("Start");
                    turn = 0;
                    win = false;
                    btn0.setEnabled(true);btn1.setEnabled(true);btn2.setEnabled(true);
                    btn3.setEnabled(true);btn4.setEnabled(true);btn5.setEnabled(true);
                    btn6.setEnabled(true);btn7.setEnabled(true);btn8.setEnabled(true);
                    txtP1.setBackground(Color.WHITE);
                    txtP2.setBackground(Color.WHITE);
                }
            }
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        btnPress(btn0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnPress(btn1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btnPress(btn2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btnPress(btn3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btnPress(btn4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        btnPress(btn5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        btnPress(btn6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        btnPress(btn7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnPress(JButton btn){
        if(btn.isEnabled() && btnStart.getText().equals("Restart") && win==false){
            btn.setEnabled(false);
            btn.setActionCommand(turn+"");
            try {
                AePlayWave aw;
                URL url = PlayAudio.class.getResource("/res/audio/open.wav");
                aw = new AePlayWave(url);
                aw.start();
             } catch (URISyntaxException ex) {
                Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
             }
            if(turn==1){
                btn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/xs.jpg")));
            }else{
                btn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/os.png")));
            }
            testWin();
        }else{
            try {
                AePlayWave aw;
                URL url = PlayAudio.class.getResource("/res/audio/draw.wav");
                aw = new AePlayWave(url);
                aw.start();
             } catch (URISyntaxException ex) {
                Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }
    
    private void testWin(){
        nTurns++;
        if(!btn0.getActionCommand().isEmpty() &&
                btn0.getActionCommand().equals(btn1.getActionCommand()) && btn1.getActionCommand().equals(btn2.getActionCommand()))
            win = true;
        if(!btn3.getActionCommand().isEmpty() &&
                btn3.getActionCommand().equals(btn4.getActionCommand()) && btn4.getActionCommand().equals(btn5.getActionCommand()))
            win = true;
        if(!btn6.getActionCommand().isEmpty() &&
                btn6.getActionCommand().equals(btn7.getActionCommand()) && btn7.getActionCommand().equals(btn8.getActionCommand()))
            win = true;
        if(!btn0.getActionCommand().isEmpty() &&
                btn0.getActionCommand().equals(btn3.getActionCommand()) && btn3.getActionCommand().equals(btn6.getActionCommand()))
            win = true;
        if(!btn1.getActionCommand().isEmpty() &&
                btn1.getActionCommand().equals(btn4.getActionCommand()) && btn4.getActionCommand().equals(btn7.getActionCommand()))
            win = true;
        if(!btn2.getActionCommand().isEmpty() &&
                btn2.getActionCommand().equals(btn5.getActionCommand()) && btn5.getActionCommand().equals(btn8.getActionCommand()))
            win = true;
        if(!btn0.getActionCommand().isEmpty() &&
                btn0.getActionCommand().equals(btn4.getActionCommand()) && btn4.getActionCommand().equals(btn8.getActionCommand()))
            win = true;
        if(!btn2.getActionCommand().isEmpty() &&
                btn2.getActionCommand().equals(btn4.getActionCommand()) && btn4.getActionCommand().equals(btn6.getActionCommand()))
            win = true;
        if(win){
            try {
                AePlayWave aw;
                URL url = PlayAudio.class.getResource("/res/audio/win.wav");
                aw = new AePlayWave(url);
                aw.start();
             } catch (URISyntaxException ex) {
                Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
             }
            JOptionPane.showMessageDialog(null, "The winner is " + (turn==1 ? txtP1.getText() : txtP2.getText()));
        }else{
            if(nTurns==9){
                try {
                AePlayWave aw;
                URL url = PlayAudio.class.getResource("/res/audio/draw.wav");
                aw = new AePlayWave(url);
                aw.start();
             } catch (URISyntaxException ex) {
                Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
             }
                JOptionPane.showMessageDialog(null, "Draw");
            }else{
                turn*=-1;
                paint();
            }
        }
    }
    
    private void paint(){
        if(turn==1){
            txtP1.setBackground(Color.RED);
            txtP2.setBackground(Color.WHITE);
        }else{
            txtP2.setBackground(Color.RED);
            txtP1.setBackground(Color.WHITE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocalGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    // End of variables declaration//GEN-END:variables
    private int turn = 0;
    private int nTurns = 0;
    private boolean win = false;
}
